apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: example-com
  namespace: mtls
spec:
  keyEncoding: pkcs8
  commonName: example.com
  secretName: example-com-tls
  isCA: true
  issuerRef:
    name: selfsigned-issuer